# Generated by Django 3.1 on 2020-08-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20200804_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='average_plate',
            new_name='average_price',
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
