# Generated by Django 3.1 on 2020-08-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_placeuserreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeuserreview',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not rated'), (1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=0),
        ),
    ]
