# Generated by Django 3.1 on 2020-08-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20200805_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeuserreview',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
