# Generated by Django 3.1 on 2020-08-05 07:57

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20200805_0034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['image_order']},
        ),
        migrations.RemoveField(
            model_name='placeimage',
            name='order_number',
        ),
        migrations.AddField(
            model_name='placeimage',
            name='image_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='place',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place'),
        ),
    ]
