# Generated by Django 3.1 on 2020-08-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20200805_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='pinyin_address',
            field=models.CharField(default='A', max_length=200),
            preserve_default=False,
        ),
    ]
