# Generated by Django 3.1 on 2020-08-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_auto_20200805_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='police_rating',
            field=models.CharField(blank=True, choices=[('PS1', '1 - No cases yet'), ('PS2', '2 - Better be cautious'), ('PS3', '3 - Periodically monitored'), ('PS4', '4 - Constantly monitored'), ('PS5', '5 - Detention cases')], default='PS1', max_length=3, null=True),
        ),
    ]
