# Generated by Django 3.1 on 2020-08-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_auto_20200805_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(blank=True, choices=[('P', 'Pub'), ('C', 'Club'), ('E', 'Eatery'), ('B', 'Bar'), ('O', 'Others')], default='O', max_length=1, null=True),
        ),
    ]
