# Generated by Django 3.1 on 2020-08-11 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_ownerstatusclaim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OwnerStatusClaim',
        ),
    ]
