# Generated by Django 3.1 on 2020-08-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_delete_ownerstatusclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='logos/'),
        ),
    ]
