# Generated by Django 3.1 on 2020-08-17 12:43

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_place_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, region=None),
        ),
    ]
