# Generated by Django 3.1 on 2020-08-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0021_auto_20200822_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='similar_places',
            field=models.ManyToManyField(related_name='_place_similar_places_+', to='places.Place'),
        ),
    ]
