# Generated by Django 3.1 on 2020-08-30 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0027_auto_20200829_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeuserreview',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='placeuserreview',
            name='author',
            field=models.ForeignKey(default=63, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
