# Generated by Django 3.1 on 2020-08-30 18:49
import random
import datetime

from django.db import migrations


def add_events(apps, schema_editor):
    time_from_range = [datetime.time(h, 00) for h in range(18, 24)]
    time_till_range = [datetime.time(h, 00) for h in range(7)]
    Event = apps.get_model('places', 'Event')
    Place = apps.get_model('places', 'Place')
    with open('random_party_titles.txt', 'r') as f:
        party_titles = [line.strip() for line in f.readlines()]

    for title in party_titles:
        time_from = random.choice(time_from_range)
        time_till = random.choice(time_till_range)
        hosting_place = random.choice([place for place in Place.objects.all()])
        fee = random.randint(20, 100)

        Event.objects.get_or_create(
            title=title,
            place=hosting_place,
            defaults={
                'fee': fee,
                'time_from': time_from,
                'time_till': time_till,
            })


def remove_events(apps, schema_editor):
    Event = apps.get_model('places', 'Event')
    Event.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0029_auto_20200830_1720'),
    ]

    operations = [
        migrations.RunPython(
            add_events,
            remove_events
        )
    ]
